name: factcheck
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - asttokens=2.4.1
  - bzip2=1.0.8
  - ca-certificates=2024.9.24
  - comm=0.2.2
  - debugpy=1.8.6
  - decorator=5.1.1
  - exceptiongroup=1.2.2
  - executing=2.1.0
  - importlib-metadata=8.5.0
  - ipykernel=6.29.5
  - ipython=8.28.0
  - jedi=0.19.1
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - ld_impl_linux-64=2.40
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.1.0
  - libgcc-ng=14.1.0
  - libgomp=14.1.0
  - libsodium=1.0.20
  - libsqlite=3.45.3
  - libstdcxx=14.1.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libzlib=1.2.13
  - matplotlib-inline=0.1.7
  - ncurses=6.4.20240210
  - nest-asyncio=1.6.0
  - openssl=3.3.2
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=24.2
  - platformdirs=4.3.6
  - prompt-toolkit=3.0.48
  - psutil=6.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - python=3.10.15
  - python-dateutil=2.9.0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - typing_extensions=4.12.2
  - wcwidth=0.2.13
  - wheel=0.44.0
  - xz=5.4.6
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - pip:
      - accelerate==1.2.1
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - annotated-types==0.7.0
      - anyio==4.8.0
      - asgiref==3.8.1
      - async-timeout==4.0.3
      - attrs==24.3.0
      - blis==1.0.2
      - bm25-pt==0.0.7
      - catalogue==2.0.10
      - certifi==2024.12.14
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpathlib==0.20.0
      - confection==0.1.5
      - contourpy==1.3.1
      - cupy-cuda12x==13.3.0
      - curated-tokenizers==0.0.9
      - curated-transformers==0.1.1
      - cycler==0.12.1
      - cymem==2.0.10
      - dataclasses-json==0.6.7
      - datasets==3.2.0
      - de-core-news-lg==3.8.0
      - deprecated==1.2.15
      - dill==0.3.8
      - distro==1.9.0
      - docarray==0.40.0
      - docker==7.1.0
      - ecdsa==0.19.0
      - einops==0.8.0
      - emoji==2.14.0
      - en-core-web-lg==3.8.0
      - en-core-web-sm==3.8.0
      - en-core-web-trf==3.8.0
      - es-core-news-lg==3.8.0
      - fastapi==0.115.6
      - fastrlock==0.8.3
      - filelock==3.16.1
      - flash-attn==2.7.2.post1
      - fonttools==4.55.3
      - fr-core-news-lg==3.8.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.66.0
      - greenlet==3.1.1
      - grpcio==1.68.0
      - grpcio-health-checking==1.68.0
      - grpcio-reflection==1.68.0
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - huggingface-hub==0.26.5
      - idna==3.10
      - ipywidgets==8.1.5
      - jcloud==0.3
      - jina==3.33.0
      - jina-hubble-sdk==0.39.0
      - jinaai==0.2.10
      - jinja2==3.1.4
      - jiter==0.8.2
      - joblib==1.4.2
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jupyterlab-widgets==3.0.13
      - kiwisolver==1.4.7
      - langchain-community==0.3.14
      - langchain-core==0.3.29
      - langchain-openai==0.2.14
      - langchain-text-splitters==0.3.5
      - langchainhub==0.1.21
      - langcodes==3.5.0
      - langsmith==0.2.10
      - language-data==1.3.0
      - loguru==0.7.3
      - marisa-trie==1.2.1
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.24.1
      - matplotlib==3.10.0
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - murmurhash==1.0.11
      - mypy-extensions==1.0.0
      - narwhals==1.28.0
      - networkx==3.4.2
      - nlp4bia==2.1.5
      - nltk==3.9.1
      - numpy==2.0.0
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.59.5
      - opentelemetry-api==1.29.0
      - opentelemetry-exporter-otlp==1.29.0
      - opentelemetry-exporter-otlp-proto-common==1.29.0
      - opentelemetry-exporter-otlp-proto-grpc==1.29.0
      - opentelemetry-exporter-otlp-proto-http==1.29.0
      - opentelemetry-exporter-prometheus==0.50b0
      - opentelemetry-instrumentation==0.50b0
      - opentelemetry-instrumentation-aiohttp-client==0.50b0
      - opentelemetry-instrumentation-asgi==0.50b0
      - opentelemetry-instrumentation-fastapi==0.50b0
      - opentelemetry-instrumentation-grpc==0.50b0
      - opentelemetry-proto==1.29.0
      - opentelemetry-sdk==1.29.0
      - opentelemetry-semantic-conventions==0.50b0
      - opentelemetry-util-http==0.50b0
      - orjson==3.10.14
      - pandas==2.2.3
      - pathspec==0.12.1
      - pillow==11.0.0
      - plotly==6.0.0
      - preshed==3.0.9
      - prometheus-client==0.21.1
      - propcache==0.2.1
      - protobuf==5.29.2
      - pt-core-news-lg==3.8.0
      - pyarrow==18.1.0
      - pyasn1==0.6.1
      - pydantic==1.10.20
      - pydantic-core==2.27.1
      - pydantic-settings==2.7.1
      - pyparsing==3.2.0
      - python-dotenv==1.0.1
      - python-jose==3.3.0
      - python-multipart==0.0.20
      - pytz==2024.2
      - pyyaml==6.0.2
      - rank-bm25==0.2.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rich==13.9.4
      - rsa==4.9
      - safetensors==0.4.5
      - scikit-learn==1.6.0
      - scipy==1.14.1
      - seaborn==0.13.2
      - sentence-transformers==3.3.1
      - shellingham==1.5.4
      - smart-open==7.0.5
      - smmap==5.0.2
      - sniffio==1.3.1
      - spacy==3.8.3
      - spacy-curated-transformers==0.3.0
      - spacy-dbpedia-spotlight==0.2.6
      - spacy-legacy==3.0.12
      - spacy-loggers==1.0.5
      - spacyfishing==0.1.8
      - spacyopentapioca==0.1.7
      - sqlalchemy==2.0.36
      - srsly==2.5.0
      - starlette==0.41.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - thinc==8.3.2
      - threadpoolctl==3.5.0
      - tiktoken==0.8.0
      - tokenizers==0.21.0
      - tomli==2.2.1
      - torch==2.5.1
      - tqdm==4.67.1
      - transformers==4.47.0
      - triton==3.1.0
      - typer==0.15.1
      - types-requests==2.31.0.6
      - types-urllib3==1.26.25.14
      - typing-inspect==0.9.0
      - tzdata==2024.2
      - urllib3==1.26.20
      - uvicorn==0.23.1
      - uvloop==0.21.0
      - wasabi==1.1.3
      - weasel==0.4.1
      - websockets==14.1
      - widgetsnbextension==4.0.13
      - wrapt==1.17.0
      - xformers==0.0.29.post1
      - xx-ent-wiki-sm==3.8.0
      - xxhash==3.5.0
      - yarl==1.18.3
